### PR TITLE
FIX: Incorrect resistor physics

### PR DESCRIPTION
**Pull request by tasseff**
While going through the physics for each of the components in GasModels, I stumbled upon a comment for the function `_calc_resistor_resistance` that pointed me to the book [Evaluating Gas Network Capacities](https://books.google.com/books?hl=en&lr=&id=3eF9BwAAQBAJ&oi=fnd&pg=PR1&ots=18ZEcTW0CT&sig=rOzOICeWei7PNJDNAsmwh5wxgJQ#v=onepage&q&f=false). If you look at Section 2.3.2, and specifically Equation (2.30), it's clear that the intended model for each resistor is a Darcy-Weisbach relationship (relating the difference of pressures to flow), not the same relationship being used for pipes (relating the difference of *squared* pressures to flow). Furthermore, it looks like the resistance being used in the implemented version was being inverted when it should not have been. I've taken a shot at addressing these issues in this pull request. For the time being, I'll keep it as a draft until we discuss further.

### CODE REVIEW

**Comment by rb004f** [comment]
@tasseff Looks like you have a travis fail

**Comment by tasseff** [comment]
@rb004f, the failures look like they're caused by a nightly Julia build and not by changes. Could you try relaunching the tests from Travis? I don't have the authority to do it.

**Comment by kaarthiksundar** [comment]
@rb004f @tasseff The nightly builds fail even on the other PR. Something to do with the length of the logs in the nightly builds. Easy fix would be to allow failures on nightly builds.

**Comment by rb004f** [comment]
Seems to be a failure in building the julia environment.... so something on the travis side.  I suspect it will be fixed in 24-48 hours....

**Pull request merged**
