### PR TITLE
REF: Style Upgrade / Refactor

### LINKED ISSUE #75: Tidy Whitespace
There is extra white space characters throughout the code.

### LINKED ISSUE #97: Update Infrastructure Models Conventions
The following convention updates should be made,

Julia/JuMP Style
- [x] `using` should be replaced by `import`
- [x] functions that modify arguments should end with `!` (exception, are model building functions like `constraint_`)
- [x] all internal use only symbols should begin with `_`
- [x] automatically export all non-internal symbols (see https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/export.jl)

Infrastructure Models
- [x] update Model types to use @def macro, remove form types
- [x] pass JuMP statuses directly in the solution https://github.com/lanl-ansi/PowerModels.jl/pull/519
- [x] revised function naming conventions, https://github.com/lanl-ansi/PowerModels.jl/issues/538 
- [x] improved ref building https://github.com/lanl-ansi/PowerModels.jl/pull/518 and https://github.com/lanl-ansi/PowerModels.jl/pull/589
- [x] user provided JuMP model https://github.com/lanl-ansi/PowerModels.jl/issues/400
- [ ] faster solution building (optional) https://github.com/lanl-ansi/PowerModels.jl/pull/539

I may have missed some smaller points, but these are the big ones.  You might want to hold off updating the solution building improvements.  At some point I would like to revisit that and possible rewrite from scratch.

### LINKED ISSUE #102: extend the build_ref function to allow arbitrary reference building
See PowerModels.jl for an example

### PR DESCRIPTION
**Pull request by pseudocubic**
Updates GasModels to follow the current styles in the InfrastructureModels ecosystem.

## Simplifies Type system and Model construction

The following types now exist:
- AbstractGasModel
- AbstractMINLPModel
- AbstractMIPModel
- AbstractMISOCPModel
- AbstractNLPModel
- AbstractLPModel
- AbstractMIModels

The following model constructors now exist:
- MINLPModel
- MIPModel
- MISOCPModel
- NLPModel
- LPModel

Struct and Type definitions now live in `src/core/types.jl`

Uses `InfrastructureModels.@def` to create macro `@gm_fields` for model constructor creation.

`GenericGasModel` constructor becomes `InitializeGasModel`

## Extends `ref` building to include `ref_extensions`

Builds ref using `InfrastructureModels.initialize_ref` and `_ref_add_core!`

## Imports

Changes `using` to `import`, packages must be explicitly called when using functions, e.g. `JSON.parse` not `parse`.

Removes Compat and LinearAlgebra from dependencies (not used)

## Exports

All functions without the prefix `_` will now be exported by default (explicit `export` unnecessary), in `src/core/export.jl`, which must be included last in `src/GasModels.jl`

## Termination Statuses

Changes "status" in results to return all MathOptInferface statuses, converting `"status"` to `"termination_status"`, `"primal_status"`, and `"dual_status"`

## Function definitions

- Changes multinetwork id `n` in functions to be e.g. `function constraint(gm, k; n::Int=gm.cnw)`
- `model_constructor` => `model_type`
- `solver` => `optimizer`
- Changes `parse_file` to have a `io::IO` version, which is the preferred Julia style, and adds an IO compatible `parse_json`

### Function name changes

Uses regex notation for some function classes

- `build_generic_model` => `build_model`
- `run_generic_model` => `run_model`
- `GenericGasModel` => `InitializeGasModel`
- `optimize!` => `JuMP.optimize!`
- `build_ref` => `ref_add_core!`
- `degree_ref` => `ref_degree!`
- `degree_ne_ref` => `ref_degree_ne!`
- `add_constraint` => `_add_constraint!`
- `apply_mass_flow_cuts` => `_apply_mass_flow_cuts`
- `apply_func` => `_apply_func!`
- `calc_(.+)` => `_calc_$1`
- `gm_component_(.+)` => `_gm_component_$1`
- `init_solution` => `_init_solution`
- `get_solution` => `solution_gf!`
- `add_setpoint` => `add_setpoint!`
- `add_(.+)_setpoint` => `add_$1_setpoint!`
- `get_start` => `comp_start_value`
- `check_network_data` => `correct_network_data!`
- `matlab_to_gasmodels` => `_matlab_to_gasmodels`
- `mlab2gm_(.+)` => `_mlab2gm_$1`
- `merge_(.+)_data` => `_merge_$1_data`
- `get_default` => `_get_default`
- `get_(.+)_solution` => `solution_$1!`

### Function additions

- `build_ref` (Generic version for building ref without initializing model)
- `_calc_max_mass_flow` (symbol version for ref calculation)

## General Style Enforcement

- Enforces two lines between functions
- Enforces no whitespace at end of lines
- Enforces docstrings for all functions (empty docstrings are okay, but must exist)
- Functions that change data should end with `!`
- Warnings and lower should be silenced during tests unless needed
- Test names should be easy to search/unique
- Test classes should have an outer scope to make it easier to identify test file

## Unit Test Notes

- Unit tests are only changed to point `"status"` => `"termination_status"`, and to update:
    - `:LocalOptimal` => `LOCALLY_SOLVED`
    - `:Optimal` => `OPTIMAL`
    - `:Infeasible` => `INFEASIBLE`
- Special functions specific to unit tests moved to `test/common.jl` and included before tests
- Other changes are all in style, not substance.

No tests were disabled or changed otherwise.

Closes #75 
Closes #97 
Closes #102

### CODE REVIEW

**Comment by rb004f** [comment]
Appears to be some conflicting files?  Probably because of a merge of the ogf formulation earlier today.  We may want to avoid renaming MISOCP to MISOC until a later merge... we have one user who is using MISOCP and we don't want to break their implementation until later

**Comment by pseudocubic** [comment]
Definitely the conflicts will be from #135, I will rebase to resolve the conflicts. 

As for MISOCP => MISOC, that was just a typo in the above text; as far as I can tell it hasn't changed in code. I have corrected it to avoid confusion.

**Comment by pseudocubic** [comment]
Once this last commit passes, this PR will be ready for merge

**Comment by ccoffrin** [comment]
@pseudocubic, also I recomend using `ref_initialize` from IMs as part of this refactor.  This helps enforce cross project `ref` conventions.

**Comment by ccoffrin** [comment]
You mention it in the list of updates, but I couldn't find it in the code.  Just double checking.

**Comment by pseudocubic** [comment]
@ccoffrin its in a couple of places, but mainly L32 of `src/core/base.jl`

**Comment by ccoffrin** [comment]
Sounds good.  Thanks for this!!!

**Comment by rb004f** [comment]
The following ref objects could be pulled out into a specific ne_ref (network expansion) function only used for expansion planning problems

:t_ne_pipes
:f_ne_pipes
:t_ne_compressors
:t_ne_compressors
:parallel_ne_pipes
:parallel_ne_compressors
:undirected_ne_pipe
:undirected_ne_compressor
:directed_ne_pipe
:directed_ne_compressor 
:ne_compressor_ref
:ne_pipe_ref

**Comment by pseudocubic** [comment]
@rb004f this is ready for merge

**Pull request merged**
