### PR TITLE
Updates for v0.7

### PR DESCRIPTION
**Pull request by tasseff**
This updates dependencies, renames `run_` methods to `solve_`, and corrects a syntactical error that propagated to GasPowerModels.jl.

### CODE REVIEW

**Comment by ccoffrin** [comment]
I would recomend holding off the `run_` to `solve_` name change until all IM packages can do it more or less at the same time.

**Comment by rb004f** [comment]
If we change the names now does it break anything?  I thought PowerModels had already completed this?

**Comment by tasseff** [comment]
All right, I've reverted back to `run_`. Once we're ready for the migration, we can just execute
```bash
find . -type f -name "*.*" -print0 | xargs -0 sed -i '' -e 's/run_/solve_/g'
```
on the corresponding packages.

**Comment by tasseff** [comment]
Oops, with the exception of `solve_time` references...

**Pull request merged**
